[package]
name = "texture-optimization"
version = "0.1.0"
authors = ["Anastasia Opara <anastasiaopara@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
kdtree = "0.5.1"
rand_pcg = "0.1.1"
rand = "0.6.4"
rustdct = "0.4.0" 
